# -*- coding: utf-8 -*-
"""LSTM_Scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXPLsdXn8ApgQcpZ8_fINRMk0xvsQy6V
"""

! pip3 install tiktoken
import importlib
import tiktoken
import re
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import random_split, DataLoader
import matplotlib.pyplot as plt
import tiktoken

print("tiktoken version:", importlib.metadata.version("tiktoken"))
tokenizer = tiktoken.get_encoding("gpt2")


with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

print("Total number of character:", len(raw_text))
print(raw_text[:99])

enc_text = tokenizer.encode(raw_text)
print(len(enc_text))
enc_sample = enc_text[50:]
print(enc_sample)


context_size = 4 #length of the input
#The context_size of 4 means that the model is trained to look at a sequence of 4 words (or tokens)
#to predict the next word in the sequence.
#The input x is the first 4 tokens [1, 2, 3, 4], and the target y is the next 4 tokens [2, 3, 4, 5]

x = enc_sample[:context_size]
y = enc_sample[1:context_size+1]

print(f"x: {x}")
print(f"y: {y}")

for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(context, "---->", desired)
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]

    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))

import torch
from torch.utils.data import Dataset, DataLoader


class DatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]





def create_dataloader_v1(txt, batch_size=4, max_length=256,
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0, split=0.9): # Added 'split' here

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = DatasetV1(txt, tokenizer, max_length, stride)

    # # Create dataloader
    # dataloader = DataLoader(
    #     dataset,
    #     batch_size=batch_size,
    #     shuffle=shuffle,
    #     drop_last=drop_last,
    #     num_workers=num_workers
    # )

    # return dataloader
    train_size = int(split * len(dataset))
    val_size = len(dataset) - train_size
    train_dataset, val_dataset = random_split(dataset, [train_size, val_size])

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=shuffle)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)

    return train_loader, val_loader, tokenizer


# import torch
# print("PyTorch version:", torch.__version__)
# dataloader = create_dataloader_v1(
#     raw_text, batch_size=1, max_length=4, stride=1, shuffle=False
# )

# data_iter = iter(dataloader)
# first_batch = next(data_iter)
# print(first_batch)
# second_batch = next(data_iter)
# print(second_batch)



# dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

# data_iter = iter(dataloader)
# inputs, targets = next(data_iter)
# print("Inputs:\n", inputs)
# print("\nTargets:\n", targets)

class LSTM(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim):
        super(LSTM, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.hidden_dim = hidden_dim

        self.Wxi = nn.Linear(embedding_dim, hidden_dim)#input gate
        self.Whi = nn.Linear(hidden_dim, hidden_dim)

        self.Wxf = nn.Linear(embedding_dim, hidden_dim)#forget gate
        self.Whf = nn.Linear(hidden_dim, hidden_dim)

        self.Wxo = nn.Linear(embedding_dim, hidden_dim)#output gate
        self.Who = nn.Linear(hidden_dim, hidden_dim)

        self.Wxg = nn.Linear(embedding_dim, hidden_dim)#candidate gate
        self.Whg = nn.Linear(hidden_dim, hidden_dim)

        self.Why = nn.Linear(hidden_dim, vocab_size)

    def forward(self, x, states):#x(batch,seq_length),states(tuple(h_prev,c_prev))

      h_prev, c_prev = states
      embedded = self.embedding(x)  # (batch, seq_len, embed_dim)
      outputs = []
      h, c = h_prev, c_prev
      for t in range(embedded.size(1)):  #lopping over the time steps/seq_length
            x_t = embedded[:, t, :] #(batch,embed_dim)

            i = torch.sigmoid(self.Wxi(x_t) + self.Whi(h))  #from the input gate
            f = torch.sigmoid(self.Wxf(x_t) + self.Whf(h))  #forget gate
            o = torch.sigmoid(self.Wxo(x_t) + self.Who(h))  #output gate
            g = torch.tanh(self.Wxg(x_t) + self.Whg(h))     #candidate cell state

            c = f * c + i * g  #pointwise operations
            h = o * torch.tanh(c)

            y = self.Why(h)
            outputs.append(y.unsqueeze(1))

      return torch.cat(outputs, dim=1), (h, c)

def train_model(model, train_loader, val_loader, vocab_size,
                num_epochs=10, lr=0.001, hidden_dim=128):

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model = model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    train_losses, val_losses = [], []
    train_accs, val_accs = [], []

    for epoch in range(num_epochs):
        model.train()
        epoch_loss, correct, total = 0, 0, 0
        # Initialize hidden and cell states
        h0 = torch.zeros(train_loader.batch_size, hidden_dim).to(device)
        c0 = torch.zeros(train_loader.batch_size, hidden_dim).to(device)
        hidden = (h0, c0)


        for inputs, targets in train_loader:
            inputs, targets = inputs.to(device), targets.to(device)

            outputs, hidden = model(inputs, hidden) # Pass initial hidden and cell states
            # Detach hidden states from the graph
            hidden = (hidden[0].detach(), hidden[1].detach())


            loss = criterion(outputs.view(-1, vocab_size), targets.view(-1))
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()

            epoch_loss += loss.item()
            preds = torch.argmax(outputs, dim=-1)
            correct += (preds == targets).sum().item()
            total += targets.numel()

        train_losses.append(epoch_loss / len(train_loader))
        train_accs.append(correct / total)

        # Validation
        model.eval()
        val_loss, correct, total = 0, 0, 0
        # Initialize hidden and cell states for validation
        h0_val = torch.zeros(val_loader.batch_size, hidden_dim).to(device)
        c0_val = torch.zeros(val_loader.batch_size, hidden_dim).to(device)
        hidden_val = (h0_val, c0_val)

        with torch.no_grad():
            for inputs, targets in val_loader:
                inputs, targets = inputs.to(device), targets.to(device)
                outputs, hidden_val = model(inputs, hidden_val) # Pass initial hidden and cell states
                loss = criterion(outputs.view(-1, vocab_size), targets.view(-1))
                val_loss += loss.item()

                preds = torch.argmax(outputs, dim=-1)
                correct += (preds == targets).sum().item()
                total += targets.numel()

        val_losses.append(val_loss / len(val_loader))
        val_accs.append(correct / total)

        print(f"Epoch {epoch+1}/{num_epochs} | "
              f"Train Loss: {train_losses[-1]:.4f}, Train Acc: {train_accs[-1]:.4f} | "
              f"Val Loss: {val_losses[-1]:.4f}, Val Acc: {val_accs[-1]:.4f}")

    return train_losses, val_losses, train_accs, val_accs

with open("the-verdict.txt", "r", encoding="utf-8") as f:
    raw_text = f.read()

train_loader, val_loader, tokenizer = create_dataloader_v1(
    raw_text, batch_size=16, max_length=32, stride=16, split=0.9 # 'split' is now a valid argument
)

vocab_size = tokenizer.n_vocab
embedding_dim, hidden_dim = 64, 128
model = LSTM(vocab_size, embedding_dim, hidden_dim)

train_losses, val_losses, train_accs, val_accs = train_model(
    model, train_loader, val_loader, vocab_size, num_epochs=20, lr=0.001, hidden_dim=hidden_dim
)

plt.figure(figsize=(10,5))
plt.plot(train_losses, label="Train Loss", color="blue")
plt.plot(val_losses, label="Val Loss", color="red")
plt.plot(train_accs, label="Train Acc", color="green")
plt.plot(val_accs, label="Val Acc", color="orange")
plt.xlabel("Epoch")
plt.ylabel("Loss / Accuracy")
plt.title("Training & Validation Loss/Accuracy")
plt.legend()
plt.show()

